config/routes.rb
Rails.application.routes.draw do
  
  resources :posts
  get 'static_pages/about' , :as => 'about_page'

  get 'static_pages/contact' , :as => 'contact_page'
  get 'static_pages/blog' , :as => 'blog_page'
  
  get 'static_pages/index'
  root 'static_pages#landing_page'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.limit(4)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :description, :image_url, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def landing_page
  	@featured_post = Post.first
  	@posts = Post.limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title>Callan's Blog</title>
	  <!-- bootstrap link -->
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	  <!-- custom css file link -->
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- javascript links go here -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- fonts go here -->
    <link href="https://fonts.googleapis.com/css?family=Bitter|Inconsolata|PT+Serif" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body>
	  <nav class="navbar navbar-default navbar-static-top">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a><%= link_to "Blog", root_url %></a>
		    </div><!-- /.navbar-header -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-right">
		        <li><%= link_to "Blog", blog_page_path %></li>
		        <li><%= link_to "About", about_page_path %></li>
		        <li><%= link_to "Contact", contact_page_path %></li>
		      </ul>
		    </div><!-- /.collapse  /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

  	<%= yield %>
	<footer>
		&copy; 2017 Callan Cook
	</footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
  <%= f.label :body %><br>
  <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<div class="container">
    <% @posts.each do |post| %>
    <div class="row" id="first-row">
      <div class="col-sm-8 col-md-4 col-lg-4" id="title-image">
        <a href="#"><h3><strong><%= post.name %></strong></h3></a>
        <%= image_tag post.image_url, :class => "post-image" %>
      </div><!-- col -->
      <div class="col-sm-8 col-md-4 col-lg-4" id="description">
        <p><%= post.description %></p>
      </div><!-- col -->
  </div><!-- row -->
  <div class="row" id="body-row">
    <div class="col-sm-8 col-md-12 col-lg-12" id="body">
      <p><%= post.body %></p>
    </div><!-- col -->
  </div><!-- row -->
  <div class="row" id="last-row">
    <div class="col-sm-12 col-md-12 col-lg-12" id="show-edit-destroy">
      <a><%= link_to 'Show', post %></a>
      <a><%= link_to 'Edit', edit_post_path(post) %></a>
      <a><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></a>
    </div><!-- col -->
  </div><!-- row -->
  <% end %>
</div><!-- container -->

<br>

<%= link_to 'New Post', new_post_path, :class => "new-post" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @post.image_url %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/about.html.erb
<h1 class="page-title">About This Blog</h1>
<div class="about">
	<p>Lorem ipsum dolor sit amet, paulo aperiri nec ad, ad elit reque suscipiantur mel, eu congue intellegat conclusionemque has. Cibo inciderint te usu, eum dissentiet referrentur no. Inani corpora eum at. Salutatus sadipscing usu ea, vel ex quod nulla concludaturque, vel ubique nominavi quaestio in. Eos persius omittantur at, duo ex velit mazim accumsan.</p>
	<p>In volumus gloriatur has, quo ad alii graecis, sale tibique mentitum id cum. Assum nonumes mea no, vidit accumsan ne mea. In liber causae facilis eam, consulatu forensibus an quo. Sea modus error partiendo eu, ius ex clita laudem nemore, veniam vituperatoribus duo ex. Id eligendi deleniti inimicus nec, qui vidit soluta iracundia ei.</p>
	<p>Mei bonorum vivendo ex, est munere nostrud voluptaria at. Vide insolens tacimates at nec, no pro nonumes habemus reprimique. Ex nam graeci imperdiet vituperata, eu his legere convenire. Eos te vide erroribus interpretaris, vocent molestie his ad. Utinam deleniti referrentur pri id. Illum aliquam inimicus te nec, vocibus disputando et vix, duo et omnis summo nostrum.</p>
</div>

app/views/static_pages/blog.html.erb
<h1 class="page-title">Blog Posts</h1>
<div class="row">
	<div class="col-xs-12 col-md-4 col-lg-4">
    <h2 class="post-header">Post #1</h2>
    <%= image_tag("https://cdn.pixabay.com/photo/2017/02/26/09/45/beatenberg-2099827_1280.jpg", height: '300', width: '300', class: "post-image") %>
  </div>
  <!-- col -->
  <div class="col-xs-12 col-md-8 col-lg-8">
    <p class="post-paragraph">Lorem ipsum dolor sit amet, paulo aperiri nec ad, ad elit reque suscipiantur mel, eu congue intellegat conclusionemque has. Cibo inciderint te usu, eum dissentiet referrentur no. Inani corpora eum at. Salutatus sadipscing usu ea, vel ex quod nulla concludaturque, vel ubique nominavi quaestio in. Eos persius omittantur at, duo ex velit mazim accumsan.</p>
  </div>
  <!-- /col -->
</div>
<!-- row -->

<div class="row">
  <div class="col-xs-12 col-md-4 col-lg-4">
    <h2 class="post-header">Post #2</h2>
    <%= image_tag("https://cdn.pixabay.com/photo/2017/02/26/09/45/beatenberg-2099827_1280.jpg", height: '300', width: '300', class: "post-image") %>
  </div>
  <!-- col -->
  <div class="col-xs-12 col-md-8 col-lg-8">
    <p class="post-paragraph">Lorem ipsum dolor sit amet, paulo aperiri nec ad, ad elit reque suscipiantur mel, eu congue intellegat conclusionemque has. Cibo inciderint te usu, eum dissentiet referrentur no. Inani corpora eum at. Salutatus sadipscing usu ea, vel ex quod nulla concludaturque, vel ubique nominavi quaestio in. Eos persius omittantur at, duo ex velit mazim accumsan.</p>
  </div>
  <!-- /col -->
</div>
<!-- row -->

<div class="row">
  <div class="col-xs-12 col-md-4 col-lg-4">
    <h2 class="post-header">Post #3</h2>
    <%= image_tag("https://cdn.pixabay.com/photo/2017/02/26/09/45/beatenberg-2099827_1280.jpg", height: '300', width: '300', class: "post-image") %>
  </div>
  <!-- col -->
  <div class="col-xs-12 col-md-8 col-lg-8">
    <p class="post-paragraph">Lorem ipsum dolor sit amet, paulo aperiri nec ad, ad elit reque suscipiantur mel, eu congue intellegat conclusionemque has. Cibo inciderint te usu, eum dissentiet referrentur no. Inani corpora eum at. Salutatus sadipscing usu ea, vel ex quod nulla concludaturque, vel ubique nominavi quaestio in. Eos persius omittantur at, duo ex velit mazim accumsan.</p>
  </div>
  <!-- /col -->
</div>
<!-- /row -->

<div class="row">
	<div class="col-xs-12 col-md-4 col-lg-4">
    <h2 class="post-header">Post #4</h2>
    <%= image_tag("https://cdn.pixabay.com/photo/2017/02/26/09/45/beatenberg-2099827_1280.jpg", height: '300', width: '300', class: "post-image") %>
  </div>
  <!-- col -->
  <div class="col-xs-12 col-md-8 col-lg-8">
    <p class="post-paragraph">Lorem ipsum dolor sit amet, paulo aperiri nec ad, ad elit reque suscipiantur mel, eu congue intellegat conclusionemque has. Cibo inciderint te usu, eum dissentiet referrentur no. Inani corpora eum at. Salutatus sadipscing usu ea, vel ex quod nulla concludaturque, vel ubique nominavi quaestio in. Eos persius omittantur at, duo ex velit mazim accumsan.</p>
  </div>
  <!-- /col -->
</div>
<!-- row -->

<div class="row">
  <div class="col-xs-12 col-md-4 col-lg-4">
    <h2 class="post-header">Post #5</h2>
    <%= image_tag("https://cdn.pixabay.com/photo/2017/02/26/09/45/beatenberg-2099827_1280.jpg", height: '300', width: '300', class: "post-image") %>
  </div>
  <!-- col -->
  <div class="col-xs-12 col-md-8 col-lg-8">
    <p class="post-paragraph">Lorem ipsum dolor sit amet, paulo aperiri nec ad, ad elit reque suscipiantur mel, eu congue intellegat conclusionemque has. Cibo inciderint te usu, eum dissentiet referrentur no. Inani corpora eum at. Salutatus sadipscing usu ea, vel ex quod nulla concludaturque, vel ubique nominavi quaestio in. Eos persius omittantur at, duo ex velit mazim accumsan.</p>
  </div>
  <!-- /col -->
</div>
<!-- row -->

<div class="row">
  <div class="col-xs-12 col-md-4 col-lg-4">
    <h2 class="post-header">Post #6</h2>
    <%= image_tag("https://cdn.pixabay.com/photo/2017/02/26/09/45/beatenberg-2099827_1280.jpg", height: '300', width: '300', class: "post-image") %>
  </div>
  <!-- col -->
  <div class="col-xs-12 col-md-8 col-lg-8">
    <p class="post-paragraph">Lorem ipsum dolor sit amet, paulo aperiri nec ad, ad elit reque suscipiantur mel, eu congue intellegat conclusionemque has. Cibo inciderint te usu, eum dissentiet referrentur no. Inani corpora eum at. Salutatus sadipscing usu ea, vel ex quod nulla concludaturque, vel ubique nominavi quaestio in. Eos persius omittantur at, duo ex velit mazim accumsan.</p>
  </div>
  <!-- /col -->
</div>
<!-- /row -->

app/views/static_pages/contact.html.erb
<div class="contact">
  <div class="header">
    <h1 class="page-title">Contact</h1>
  </div>
  <!-- end header --> 
  <div class="info">
	  <div class="email">
	    <p><span class="glyphicon glyphicon-envelope"></span>callan.c.cook@gmail.com</p>
	  </div>
	  <!-- end email -->
	  <div class="address">
	    <p><span class="glyphicon glyphicon-home"></span>Sharpsburg, GA</p>
	  </div>
	  <!-- end address -->
	  <div class="phone">
	    <p><span class="glyphicon glyphicon-phone"></span>770.241.8120</p>
	  </div>
	  <!-- end phone -->
  </div>
  <!-- end info -->
</div>
<!-- end contact -->

app/views/static_pages/index.html.erb
<h1>This Is A Blog</h1>
<p>made using ruby on rails</p>

app/views/static_pages/landing_page.html.erb
<!-- image carousel -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  	<% @posts.each do |post| %>
    <div class="item<%= " active" if post == @posts.first %>">
      <%= image_tag(post.image_url) %>
      <div class="carousel-caption">
        <%= post.name %>
      </div>
    </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<h2>Featured Blog Post</h2>
<%= @featured_post.name %>